!**********************************************************************************
!  SOIL MOISTURE DROUGHT INDEX
!  PURPOSE:  
!            Estimate the soil moisture index using daily values generated by mHM
!  AUTHOR:   
!            Luis E. Samaniego-Eguiguren, UFZ, 02-2011
!  ALGORITHM: 
!            1) Read binp files daily
!            2) Estimate monthly values of mHM-SM(sum over all layers) for each grid cell
!               - write them into netCDF
!            3) Estimate the empirical density function for each grid cell
!               using a non-parametric approach,  e.g. kernel smoother whose
!               bandwith is estimated with an unbiased cross-validation criterium
!            4) Estimate the mHM-drought index
!                    q(s) = \int_a^s f(s)ds 
!                    where:
!                         s = total soil moisture in mm over all soil layers in mHM
!                         a = lower limit of soil moisture a a given grid 
!                       q(s)= quantile corresponding to s
!            5) Estimate the following indices
!               - start
!               - duration
!               - magnitud
!               - severity
!               - affected area
!            6) Save results in netCDF format
!      
!  UPDATES:
!          Created   Sa  15.02.2011            main structure
!                    Sa  20.02.2011            debuging
!                    Sa  25.05.2011            v3. scenarios
!                    Sa  02.04.2012            v4. read COSMO SM
!                    Sa  22.06.2012            v4. read WRF-NOAH SM 
!**********************************************************************************
program SM_Drought_Index
  use mo_kind,          only : i4
  use InputOutput,      only : ReadDataMain, WriteNetCDF, &
                               WritebinP, SMI_flag, nDurations, durList, &
                               writeResultsCluster, WriteResultsBasins
  use SMIndex,          only : calSMI
  implicit none
  integer(i4)                :: d
  !
  call ReadDataMain
  !
  print*, 'FINISHED READING'
  ! estimate/re-estimate SMI
  if (SMI_flag ==1 .or. SMI_flag == 3 .or. SMI_flag == 4 .or. SMI_flag == 5 ) then
     call WriteNetCDF(1)
     call WritebinP(1)
     call calSMI
     call WriteNetCDF(2)
     call WritebinP(2)
  end if
  ! drought indicator 
  call droughtIndicator
  call WriteNetCDF(3)

  ! write SMI average over major basins
  !call WriteResultsBasins
  
  !goto 999  ! ONLY for scenarios

  ! cluster indentification
  call ClusterEvolution
  call WriteNetCDF(4)
  ! statistics  
  call ClusterStats
  !
  ! SAD analysis
  do d = 1, nDurations
     call calSAD(d)
     call WriteNetCDF(5,durList(d))
  end do
  ! write results
  call writeResultsCluster(1)
  !
  ! write SMI average over major basins
  call WriteResultsBasins
  999 call clean
end program SM_Drought_Index
